# Generated by Django 2.1.7 on 2019-03-05 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('2844d18e-6c0d-4bbe-88ed-e5c23f2a413f'), editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('d2e995a4-8fbd-4d34-a4f8-135c51aebeb4'), editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('category', models.ManyToManyField(to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bad75109-2f6f-439c-a7ed-5cc078a336c5'), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
            ],
        ),
        migrations.CreateModel(
            name='UserSaltTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.UUIDField(default=uuid.UUID('4a70f485-41a9-479e-9965-30daabac51b0'), editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='salt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserSaltTable'),
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='app.UserAccount'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='app.UserAccount'),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserAccount'),
        ),
    ]
