# Generated by Django 2.1.7 on 2019-03-05 01:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('4a5510b9-0d94-4b23-b29a-62f4df988e52'), editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('2b5236e3-4ffa-4d99-ba92-135d8bc5c564'), editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2e0aba6c-148b-431c-a252-44b96caa1bdb'), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='app.UserAccount'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='app.UserAccount'),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserAccount'),
        ),
    ]
