# Generated by Django 2.1.7 on 2019-03-04 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('67d30cc2-4e30-4af3-9993-3c7252e79168'), editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('883f2404-22f3-40cb-b94f-18024cd3db83'), editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bd9a5397-2fcb-41eb-b320-1cce4b14c7c1'), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='app.UserAccount'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='app.UserAccount'),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserAccount'),
        ),
    ]
