# Generated by Django 2.1.7 on 2019-03-05 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49f45035-a281-40d0-85ce-bd2183967522'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d648079-6bd1-4392-a114-8f46c6b96e4b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad801a31-4fff-4798-8f66-402b01b5a6d7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersalttable',
            name='salt',
            field=models.UUIDField(default=uuid.UUID('7fa9f91a-93f9-45a8-83ea-6ae81c98365a'), editable=False),
        ),
    ]
