# Generated by Django 2.1.7 on 2019-03-08 03:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e3ea09c-9083-455f-9181-1a8dd4d101ef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82ff3c06-9ca8-4b58-b9ea-1f1835c0b03f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45098182-0fef-407b-a725-2abc3fd1452f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersalttable',
            name='salt',
            field=models.UUIDField(default=uuid.UUID('23399de2-ca18-4ddc-afd4-978402c211f1')),
        ),
    ]
