# Generated by Django 2.1.7 on 2019-03-04 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e06b34d5-dc49-4efc-9bf3-4053cf512ce0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0945dbfe-45d6-4e34-a9fc-991abeeae37a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e400191-5e0c-465a-9da6-f4f0f1be901c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
