# Generated by Django 2.1.7 on 2019-03-04 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d75d811-fe0e-4047-9657-512b40ce862d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a4d9325-2df4-48d7-9f66-5b19c2cb4c57'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('70d66a0b-3cd9-43c9-ad8f-bc2b14c63d88'), editable=False, primary_key=True, serialize=False),
        ),
    ]
