# Generated by Django 2.1.7 on 2019-03-05 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190305_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8977720b-7640-4444-9301-9288f28ddc5b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a34bf436-5df9-45d2-8a6f-ed53ecfc7ac8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13745add-e970-4f2d-a928-3e4858ad37a3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersalttable',
            name='salt',
            field=models.UUIDField(default=uuid.UUID('3be9cf36-3422-48c3-8934-2b0f99f4f5cc'), editable=False),
        ),
    ]
