# Generated by Django 2.1.7 on 2019-03-04 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190304_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46616d72-10af-472b-b875-f1770a87ccd4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('96107574-3e33-4b2a-99a6-1c4fd6aba7bf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='participants', to='app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80b7724a-de0e-4380-877c-840700347d34'), editable=False, primary_key=True, serialize=False),
        ),
    ]
