# Generated by Django 2.1.7 on 2019-03-08 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190308_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60b0b72f-0cd2-41e6-b4b0-db2413347e07'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90fc9560-cd97-4f85-a3c3-4fdda6e6a440'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab61f1ab-c403-43b3-b720-636c557aebf9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersalttable',
            name='salt',
            field=models.UUIDField(default=uuid.UUID('531d8097-bc4f-4186-b428-9e1b7fc85ea7')),
        ),
    ]
