# Generated by Django 2.1.7 on 2019-03-06 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190306_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc2cc5fc-e6c4-40bb-8b6f-9539ba94c4e8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8732043f-a05a-49cb-95ff-a89b6e17ae45'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f33f34a7-7459-4b4c-9929-18c3622c548a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersalttable',
            name='salt',
            field=models.UUIDField(default=uuid.UUID('15420463-a9c7-4f23-bf8e-07c35490ef59')),
        ),
    ]
