# Generated by Django 2.1.7 on 2019-03-04 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190304_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f596f8c0-b2b7-4550-82a0-20df4bca5719'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4cdda9f-b933-4850-9633-5e912c2a4c77'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73fd5d24-4dd3-4f05-b0a2-cdc41df6b79f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
