# Generated by Django 2.1.7 on 2019-03-06 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190306_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2fae36e-23dc-4660-9268-27c40fecc208'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3f3f7af-5aa3-41f1-9787-039a3cd8d751'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb759dfd-ed0e-4e5f-b7b5-051f6e4f70c6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersalttable',
            name='salt',
            field=models.UUIDField(default=uuid.UUID('a5f1c8be-4d7a-4e84-a9f2-0de28bc31240')),
        ),
    ]
