# Generated by Django 2.1.7 on 2019-03-05 08:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190305_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ba16179-7cf4-4285-809e-1ff82da94404'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fec31bd5-1f71-4f52-9a35-2096fdbf44de'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('958f7123-52a7-437b-991d-b7aed1903c84'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='salt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.UserSaltTable'),
        ),
        migrations.AlterField(
            model_name='usersalttable',
            name='salt',
            field=models.UUIDField(default=uuid.UUID('609f740f-ae0e-453a-bd4d-6c313e68ee1f')),
        ),
    ]
