# Generated by Django 2.1.7 on 2019-03-04 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55cc25b1-0bdb-42f8-a37d-d8e2ee3512b3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e96e5f5-7986-4da7-97d7-c26fa9ae1893'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02f13d76-fb60-4fe2-9ea1-8e96e4b96afc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
