version: "3.0"
services:
  db_service:
    image: bitnami/mysql:5.7
    env_file:
      - .db.env
#    ports:
#      - "3306:3306"
    networks:
      - webnet
    deploy:
      replicas: 1
    volumes:
      - db_vol:/bitnami/mysql/data

  web_app:
    image: ${ENTRY_TASK_IMAGE}
    env_file:
      - .env
    networks:
      - webnet
    deploy:
      replicas: 1
#    ports:
#      - "80:8000"
    depends_on:
      - db_service
    volumes:
      - image_vol:/app/Images
      - static_vol:/app/src/static

  nginx_service:
    image: nginx:1.14
#    restart: always
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - image_vol:/app/src/Images:ro
      - static_vol:/app/src/static:ro
    ports:
      - "80:80"
    depends_on:
      - web_app
    networks:
      - webnet
    command: ["nginx", "-g", "daemon off;"]

networks:
  webnet:

volumes:
  db_vol:
  image_vol:
  static_vol:

